import type { RitualId } from "./rituals";

export interface Product {
  id: string;
  world: RitualId;
  sub: string;
  name: { en: string; fr: string };
  short: { en: string; fr: string };
  lede?: { en: string; fr: string };
  hero?: boolean;
  tags: string[];
  moq: number;
  formats: string[];
  lead: string;
  origin?: string;
  ritual?: string;
  images: string[];
  application?: Array<{ en: [string, string]; fr: [string, string] }>;
  proof?: string[];
  related?: string[];
}

// Source of truth: Barbaria Morocco B2B Catalogue (Apr 2026, 15 pages,
// 6 gammes × 6 products = 36 SKUs) + 3 curated Heritage packs added in
// Sprint 1.5. All copy adapted from the client's catalogue descriptions;
// EN translations produced in this sprint and aligned with the maison's
// editorial voice. Lead times reflect the catalogue's commercial terms
// ("7-14 j Maroc, 10-21 j International").

export const PRODUCTS: Product[] = [
  // ============================================================
  // HAMMAM RITUAL, Gamme 03 (scrubs, masks) + Gamme 05 (beldi soaps)
  // ============================================================

  // --- Gamme 03: Rituel Hammam (6) ---
  {
    id: "gommage-nila",
    world: "hammam",
    sub: "scrubs",
    name: { en: "Nila, Argan & Orange Blossom Scrub", fr: "Gommage Nila, Argan & Fleur d'Oranger" },
    short: { en: "Signature Barbaria scrub.", fr: "Gommage signature Barbaria." },
    lede: {
      en: "The signature scrub of the maison. Nila (pure indigo) blended with argan oil and orange blossom water. A deep blue-black powder that turns the pot into a treasure object. Purifies in depth, draws out impurities, leaves the skin renewed.",
      fr: "Le gommage signature de la maison. Nila (indigo pur) mélangée à l'huile d'argan et à l'eau de fleur d'oranger. Une poudre bleue-noire qui fait du pot un objet précieux. Purifie en profondeur, élimine les impuretés, laisse une peau neuve.",
    },
    hero: true,
    ritual: "Signature Barbaria",
    tags: ["Nila (Indigo)", "Pure Argan", "Orange Blossom", "Exfoliating", "Pot 200 g", "100% Natural", "Cooperative-made"],
    moq: 60,
    formats: ["Pot 100 g", "Pot 200 g"],
    lead: "2 weeks",
    origin: "Marrakech atelier",
    images: ["/brand_photos/sugar-scrub-hammam.jpg", "/brand_photos/sugar-scrub-ingredients.jpg", "/brand_photos/sugar-scrub-stacked.jpg"],
    application: [
      { en: ["Steam", "Open the pores in the hammam vapour for 10 minutes."], fr: ["Vapeur", "Ouvrir les pores à la vapeur du hammam pendant 10 minutes."] },
      { en: ["Massage", "Apply on damp warm skin, circle in for 5 minutes."], fr: ["Masser", "Appliquer sur peau humide et chaude, masser en cercles 5 minutes."] },
      { en: ["Kessa", "Glove down, rinse, finish with a hydrosol mist."], fr: ["Kessa", "Gommer au kessa, rincer, finir avec un hydrolat."] },
    ],
  },
  {
    id: "gommage-aker-fassi",
    world: "hammam",
    sub: "scrubs",
    name: { en: "Aker Fassi & Rose Scrub", fr: "Gommage Aker Fassi & Rose" },
    short: { en: "Radiance and luminosity.", fr: "Éclat et luminosité." },
    lede: {
      en: "Aker fassi (Fès pomegranate-bark pigment) blended with Dades rose water and cane sugar. Exfoliates with grace, illuminates, leaves the skin tinted with a natural rose hue. Highly favoured in spa protocols.",
      fr: "Aker fassi (pigment d'écorce de grenadier de Fès) mélangé à l'eau de rose du Dadès et au sucre de canne. Exfolie en douceur, illumine, laisse la peau teintée d'un rose naturel. Très apprécié en protocole spa.",
    },
    tags: ["Aker Fassi", "Damask Rose", "Exfoliating", "Anti-age", "Pot 200 g", "Cooperative-made"],
    moq: 60,
    formats: ["Pot 100 g", "Pot 200 g"],
    lead: "2 weeks",
    origin: "Fès atelier",
    images: ["/brand_photos/sugar-scrub-ingredients.jpg"],
  },
  {
    id: "masque-ghassoul-rose",
    world: "hammam",
    sub: "masks",
    name: { en: "Ghassoul & Rose Water Mask", fr: "Masque Ghassoul & Eau de Rose" },
    short: { en: "Ancestral purification.", fr: "Purification ancestrale." },
    lede: {
      en: "Ghassoul, the volcanic clay of the Middle Atlas (unique to Morocco), blended with pure rose water from the Dades. Mix to a cream, apply, draw out impurities, tighten pores, leave the skin velvet-soft.",
      fr: "Ghassoul, l'argile volcanique du Moyen Atlas (unique au Maroc), mélangé à l'eau de rose pure du Dadès. Mélanger jusqu'à consistance crémeuse, appliquer, absorber les impuretés, resserrer les pores, laisser une peau veloutée.",
    },
    tags: ["Ghassoul", "Damask Rose", "Purifying", "Pot 200 g", "100% Natural", "Cooperative-made"],
    moq: 60,
    formats: ["Pot 100 g", "Pot 200 g"],
    lead: "2 weeks",
    origin: "Middle Atlas",
    images: ["/brand_photos/sugar-scrub-hammam.jpg"],
  },
  {
    id: "gommage-sidr",
    world: "hammam",
    sub: "scrubs",
    name: { en: "Sidr & Argan Scrub", fr: "Gommage Sidr & Argan" },
    short: { en: "Ancestral recipe.", fr: "Recette ancestrale." },
    lede: {
      en: "Sidr leaf powder (sacred jujube) blended with argan oil and natural honey. Used for centuries as a sacred cleanser in Moroccan and Islamic tradition. Cleanses and fortifies, strengthens the skin's barrier.",
      fr: "Poudre de feuilles de sidr (jujubier sacré) mélangée à l'huile d'argan et au miel naturel. Utilisée depuis des siècles comme nettoyant sacré dans la tradition marocaine et islamique. Nettoie et fortifie, renforce la barrière cutanée.",
    },
    tags: ["Sidr", "Pure Argan", "Honey", "Purifying", "Pot 200 g", "Cooperative-made"],
    moq: 60,
    formats: ["Pot 100 g", "Pot 200 g"],
    lead: "2 weeks",
    images: ["/brand_photos/sugar-scrub-stacked.jpg"],
  },
  {
    id: "gommage-levres",
    world: "hammam",
    sub: "scrubs",
    name: { en: "Aker Fassi & Honey Lip Scrub", fr: "Gommage Lèvres Aker Fassi & Miel" },
    short: { en: "Lip beauty, the Moroccan way.", fr: "Beauté des lèvres à la marocaine." },
    lede: {
      en: "Aker fassi pigment, natural honey and fine sugar. The most traditional lip care of Moroccan women. Exfoliates gently and tints the lips a natural rose, no makeup required.",
      fr: "Aker fassi, miel naturel et sucre fin. Le soin lèvres le plus traditionnel des femmes marocaines. Exfolie en douceur et colore les lèvres en rose naturel, sans maquillage.",
    },
    tags: ["Aker Fassi", "Honey", "Exfoliating", "Pot 100 g", "Cooperative-made"],
    moq: 80,
    formats: ["Pot 100 g"],
    lead: "2 weeks",
    images: ["/brand_photos/packaging-1.jpg"],
  },
  {
    id: "masque-ghassoul-argan",
    world: "hammam",
    sub: "masks",
    name: { en: "Ghassoul & Argan Body Mask", fr: "Masque Corps Ghassoul & Argan" },
    short: { en: "Complete hammam body care.", fr: "Soin corps complet du hammam." },
    lede: {
      en: "Powdered ghassoul, argan oil and orange blossom water. A full-body mask that follows the scrub and seals the hammam protocol. Skin emerges ultra-soft and softly fragranced.",
      fr: "Ghassoul en poudre, huile d'argan et eau de fleur d'oranger. Masque corps complet qui suit le gommage et scelle le protocole hammam. Peau ultra-douce et délicatement parfumée.",
    },
    tags: ["Ghassoul", "Pure Argan", "Orange Blossom", "Purifying", "Pot 200 g", "Cooperative-made"],
    moq: 50,
    formats: ["Pot 200 g"],
    lead: "2 weeks",
    images: ["/brand_photos/sugar-scrub-hammam.jpg"],
  },

  // --- Gamme 05: Savons Noirs Beldi (6) ---
  {
    id: "savon-beldi-nila",
    world: "hammam",
    sub: "soaps",
    name: { en: "Nila & Orange Blossom Beldi Soap", fr: "Savon Beldi Nila & Fleur d'Oranger" },
    short: { en: "Signature hammam soap.", fr: "Savon signature du hammam." },
    lede: {
      en: "The signature beldi of the range. Fermented black-olive base, pure indigo and orange blossom water. A magnificent natural blue-black hue. Detoxifies in depth, prepares the skin for the scrub.",
      fr: "Le savon signature de la gamme. Base d'olive noire fermentée, indigo pur et eau de fleur d'oranger. Une couleur bleutée magnifique. Détoxifie en profondeur, prépare la peau au gommage.",
    },
    hero: true,
    ritual: "Signature Hammam",
    tags: ["Beldi Olive", "Nila (Indigo)", "Orange Blossom", "Purifying", "Pot 200 g", "100% Natural", "Cooperative-made"],
    moq: 100,
    formats: ["Pot 100 g", "Pot 200 g", "Pot 250 g"],
    lead: "2 weeks",
    images: ["/brand_photos/savon-noir-2.jpg", "/brand_photos/savon-noir-3.jpg"],
    application: [
      { en: ["Apply", "Spread on damp warm skin in the hammam."], fr: ["Appliquer", "Étaler sur peau humide et chaude au hammam."] },
      { en: ["Wait", "Let the soap rest 5 to 10 minutes."], fr: ["Reposer", "Laisser poser de 5 à 10 minutes."] },
      { en: ["Glove", "Exfoliate with the kessa, rinse warm."], fr: ["Kessa", "Gommer au kessa, rincer à l'eau tiède."] },
    ],
  },
  {
    id: "savon-beldi-aker-fassi",
    world: "hammam",
    sub: "soaps",
    name: { en: "Aker Fassi & Rose Beldi Soap", fr: "Savon Beldi Aker Fassi & Rose" },
    short: { en: "Radiance and complexion.", fr: "Éclat et teint." },
    lede: {
      en: "Beldi base with aker fassi (pomegranate pigment) and Dades rose water. An exfoliating, illuminating soap. Natural rose hue. Highly effective on face and body in the hammam protocol.",
      fr: "Base beldi avec aker fassi (pigment de grenadier) et eau de rose du Dadès. Un savon exfoliant et illuminateur. Couleur rose naturelle. Très efficace sur visage et corps dans le protocole hammam.",
    },
    tags: ["Beldi Olive", "Aker Fassi", "Damask Rose", "Anti-age", "Pot 200 g", "Cooperative-made"],
    moq: 100,
    formats: ["Pot 100 g", "Pot 200 g"],
    lead: "2 weeks",
    images: ["/brand_photos/savon-noir-3.jpg"],
  },
  {
    id: "savon-beldi-saad-musc",
    world: "hammam",
    sub: "soaps",
    name: { en: "S'ad & White Musk Beldi Soap", fr: "Savon Beldi S'ad & Musc Blanc" },
    short: { en: "Gulf luxury, alcohol-free.", fr: "Luxe du Golfe, sans alcool." },
    lede: {
      en: "Beldi base, S'ad (chufa) oil and natural white musk. A warm, woody, enveloping fragrance. Alcohol-free, deeply appreciated in Gulf cultures. The most luxurious soap of the range.",
      fr: "Base beldi, huile de S'ad (souchet) et musc blanc naturel. Un parfum chaud, boisé, enveloppant. Sans alcool, très apprécié dans la culture arabe. Le savon le plus luxueux de la gamme.",
    },
    ritual: "Golfe +++",
    tags: ["Beldi Olive", "S'ad (Chufa)", "White Musk", "Purifying", "Pot 200 g"],
    moq: 100,
    formats: ["Pot 100 g", "Pot 200 g"],
    lead: "2 weeks",
    images: ["/brand_photos/savon-noir-4.jpg"],
  },
  {
    id: "savon-beldi-ghassoul",
    world: "hammam",
    sub: "soaps",
    name: { en: "Ghassoul & Argan Beldi Soap", fr: "Savon Beldi Ghassoul & Argan" },
    short: { en: "Complete and nourishing.", fr: "Complet et nourrissant." },
    lede: {
      en: "Triple action: beldi cleanses, ghassoul purifies and absorbs, argan nourishes. The most complete Moroccan hammam soap. Ideal for dry and combination skin, suitable for the whole family.",
      fr: "Triple action: la base beldi nettoie, le ghassoul purifie et absorbe, l'argan nourrit. Le savon le plus complet du hammam marocain. Idéal pour peaux sèches et mixtes, bon pour toute la famille.",
    },
    tags: ["Beldi Olive", "Ghassoul", "Pure Argan", "Hydrating", "Pot 200 g", "Cooperative-made"],
    moq: 100,
    formats: ["Pot 100 g", "Pot 200 g"],
    lead: "2 weeks",
    images: ["/brand_photos/savon-noir-2.jpg"],
  },
  {
    id: "savon-beldi-sidr",
    world: "hammam",
    sub: "soaps",
    name: { en: "Sidr & Black Seed Beldi Soap", fr: "Savon Beldi Sidr & Nigelle" },
    short: { en: "Special haircare soap.", fr: "Spécial capillaire." },
    lede: {
      en: "A beldi formulated specifically for washing hair at the hammam. Sidr (sacred jujube), black seed oil and fermented olive. A natural alternative to shampoo, anti-dandruff, brings shine and lightness.",
      fr: "Une base beldi conçue spécialement pour laver les cheveux au hammam. Sidr (jujubier sacré), huile de nigelle et olive fermentée. Alternative naturelle au shampoing, antipelliculaire, brillance et légèreté.",
    },
    tags: ["Beldi Olive", "Sidr", "Black Seed", "Fortifying", "Pot 200 g"],
    moq: 100,
    formats: ["Pot 100 g", "Pot 200 g"],
    lead: "2 weeks",
    images: ["/brand_photos/savon-noir-3.jpg"],
  },
  {
    id: "savon-beldi-henne",
    world: "hammam",
    sub: "soaps",
    name: { en: "Henna & Jasmine Beldi Soap", fr: "Savon Beldi Henné & Jasmin" },
    short: { en: "Floral fragrance.", fr: "Parfum floral." },
    lede: {
      en: "Beldi base with pure natural henna (fortifying) and Moroccan jasmine (fragrancing). A soft natural orange hue. Strengthens skin and hair while perfuming with fresh jasmine.",
      fr: "Base beldi avec henné naturel pur (fortifiant) et jasmin du Maroc (parfumant). Une couleur orangée douce naturelle. Renforce peau et cheveux tout en parfumant au jasmin frais.",
    },
    tags: ["Beldi Olive", "Henna", "Jasmine", "Fortifying", "Pot 200 g"],
    moq: 100,
    formats: ["Pot 100 g", "Pot 200 g"],
    lead: "2 weeks",
    images: ["/brand_photos/savon-noir-4.jpg"],
  },

  // ============================================================
  // BOTANICAL CARE, Gamme 01 (oils) + Gamme 02 (serums) + Gamme 04 (hydrosols) + Gamme 06 (massage)
  // ============================================================

  // --- Gamme 01: Huiles Pures (6) ---
  {
    id: "huile-argan",
    world: "botanical",
    sub: "oils",
    name: { en: "Pure Argan Oil", fr: "Huile d'Argan Pure" },
    short: { en: "Liquid gold from Morocco.", fr: "L'or liquide du Maroc." },
    lede: {
      en: "Morocco's greatest oil. Cold-pressed, first mechanical press, no solvents. Golden, light, non-greasy. Rich in vitamin E and omega 6-9. Deep hydration, anti-age, complexion glow.",
      fr: "La plus grande huile marocaine. Extraite à froid, première pression mécanique, sans solvant. Dorée, légère, non grasse. Riche en vitamine E et oméga 6-9. Hydratation profonde, anti-âge, éclat du teint.",
    },
    hero: true,
    ritual: "Or Liquide du Maroc",
    tags: ["Pure Argan", "Hydrating", "Anti-age", "Amber glass", "30 ml", "50 ml", "100 ml", "Cold-pressed", "Cooperative-made"],
    moq: 50,
    formats: ["30 ml", "50 ml", "100 ml"],
    lead: "2 weeks",
    origin: "Taliouine, Souss",
    images: ["/brand_photos/argan-oil-dropper.jpg", "/brand_photos/brand-lifestyle-1.jpg"],
    application: [
      { en: ["Cleanse", "Wash the face with lukewarm water, pat dry."], fr: ["Nettoyer", "Laver le visage à l'eau tiède, sécher en tapotant."] },
      { en: ["Drop", "Three to five drops into the palm, warm between hands."], fr: ["Déposer", "Trois à cinq gouttes dans la paume, réchauffer entre les mains."] },
      { en: ["Press", "Press into face, neck and décolleté, morning and evening."], fr: ["Presser", "Presser sur visage, cou et décolleté, matin et soir."] },
    ],
  },
  {
    id: "huile-figue-barbarie",
    world: "botanical",
    sub: "oils",
    name: { en: "Pure Prickly Pear Seed Oil", fr: "Huile de Figue de Barbarie Pure" },
    short: { en: "1 ton of fruit per litre.", fr: "1 tonne de fruits par litre." },
    lede: {
      en: "Ultra rare, premium. The world's richest plant-based source of vitamin E. 1 ton of prickly pears for 1 litre of oil, cold mechanical extraction. Deep cellular regeneration, intense anti-wrinkle action.",
      fr: "Ultra rare, premium. L'huile la plus riche en vitamine E du monde végétal. 1 tonne de figues pour 1 litre d'huile, extraction mécanique à froid. Régénération cellulaire profonde, anti-rides intense.",
    },
    ritual: "Ultra Rare",
    tags: ["Prickly Pear", "Anti-age", "Amber glass", "30 ml", "50 ml", "Cold-pressed", "Cooperative-made"],
    moq: 40,
    formats: ["30 ml", "50 ml"],
    lead: "3 weeks",
    origin: "Souss-Massa",
    images: ["/brand_photos/brand-lifestyle-2.jpg"],
  },
  {
    id: "huile-saad",
    world: "botanical",
    sub: "oils",
    name: { en: "Pure S'ad (Chufa) Oil", fr: "Huile de S'ad (Souchet) Pure" },
    short: { en: "Ancestral feminine tradition.", fr: "Tradition féminine ancestrale." },
    lede: {
      en: "Chufa seed oil with a unique earthy-sweet natural fragrance. Used by Moroccan women as a body perfume and hair treatment for centuries. Gentle on sensitive skin.",
      fr: "Huile de souchet odorant au parfum naturel terreux et doux unique. Utilisée par les femmes marocaines comme parfum corps et soin capillaire depuis des siècles. Douce pour peaux sensibles.",
    },
    ritual: "Tradition Ancestrale",
    tags: ["S'ad (Chufa)", "Soothing", "Amber glass", "30 ml", "50 ml", "Cold-pressed"],
    moq: 40,
    formats: ["30 ml", "50 ml"],
    lead: "2 weeks",
    images: ["/brand_photos/brand-lifestyle-3.jpg"],
  },
  {
    id: "huile-ricin",
    world: "botanical",
    sub: "oils",
    name: { en: "Pure Castor Oil", fr: "Huile de Ricin Pure" },
    short: { en: "Multi-use, cold-pressed.", fr: "Multi-usage, pressée à froid." },
    lede: {
      en: "Cold-pressed, thick and nourishing. Stimulates hair growth, strengthens eyebrows and lashes, deeply moisturises dry areas. 100% pure, no additives or preservatives.",
      fr: "Pressée à froid, épaisse et nourrissante. Stimule la pousse des cheveux, renforce sourcils et cils, hydrate intensément les zones sèches. 100% pure, sans additif ni conservateur.",
    },
    tags: ["Castor", "Hydrating", "Fortifying", "Amber glass", "50 ml", "100 ml", "Cold-pressed"],
    moq: 40,
    formats: ["50 ml", "100 ml"],
    lead: "2 weeks",
    images: ["/brand_photos/brand-lifestyle-4.jpg"],
  },
  {
    id: "huile-rose",
    world: "botanical",
    sub: "oils",
    name: { en: "Pure Rose Oil", fr: "Huile de Rose Pure" },
    short: { en: "Luxury, Dades Valley.", fr: "Luxe, Vallée du Dadès." },
    lede: {
      en: "Rosa Damascena essential oil from the Dades Valley. A few drops are enough. One of the most precious oils in the world: powerful anti-wrinkle, regenerating, exceptional floral fragrance.",
      fr: "Huile essentielle de Rosa Damascena de la vallée du Dadès. Quelques gouttes suffisent. L'une des plus chères au monde, anti-rides puissante, régénérante, parfum floral exceptionnel.",
    },
    ritual: "Luxe Dadès",
    tags: ["Damask Rose", "Anti-age", "Amber glass", "30 ml", "Cooperative-made"],
    moq: 30,
    formats: ["30 ml"],
    lead: "3 weeks",
    origin: "Dades Valley",
    images: ["/brand_photos/brand-lifestyle-5.jpg"],
  },
  {
    id: "huile-nigelle",
    world: "botanical",
    sub: "oils",
    name: { en: "Pure Black Seed Oil", fr: "Huile de Nigelle Pure" },
    short: { en: "The blessed seed (Habba Sawda).", fr: "La graine bénie (Habba Sawda)." },
    lede: {
      en: "Cold-pressed, a powerful natural anti-inflammatory. Very high demand in the Arab world for its virtues. Anti-hair loss, purifies the scalp, supports problematic skin.",
      fr: "Pressée à froid, anti-inflammatoire naturelle puissante. Très forte demande dans le monde arabe pour ses vertus. Anti-chute, purifie le cuir chevelu, peaux problématiques.",
    },
    ritual: "Golfe +++",
    tags: ["Black Seed", "Soothing", "Purifying", "Amber glass", "30 ml", "50 ml"],
    moq: 50,
    formats: ["30 ml", "50 ml"],
    lead: "2 weeks",
    images: ["/brand_photos/brand-lifestyle-1.jpg"],
  },

  // --- Gamme 02: Sérums Concentrés (6) ---
  {
    id: "serum-anti-age",
    world: "botanical",
    sub: "serums",
    name: { en: "Royal Anti-Age Serum", fr: "Sérum Anti-Âge Royal" },
    short: { en: "The trio: prickly pear, argan, rose.", fr: "Le trio: figue, argan, rose." },
    lede: {
      en: "The most powerful trio: prickly pear regenerates cells, argan nourishes deeply, rose illuminates and plumps. Visible results in four weeks.",
      fr: "Le trio le plus puissant: la figue de barbarie régénère les cellules, l'argan nourrit en profondeur, la rose illumine et repulpe. Résultat visible en quatre semaines.",
    },
    ritual: "Best-seller Potentiel",
    tags: ["Prickly Pear", "Pure Argan", "Damask Rose", "Anti-age", "Amber glass", "30 ml"],
    moq: 40,
    formats: ["30 ml", "50 ml"],
    lead: "3 weeks",
    images: ["/brand_photos/brand-lifestyle-2.jpg"],
    application: [
      { en: ["Cleanse", "On clean skin in the evening."], fr: ["Nettoyer", "Sur peau nettoyée le soir."] },
      { en: ["Drop", "Three to four drops into the palm."], fr: ["Déposer", "Trois à quatre gouttes dans la paume."] },
      { en: ["Massage", "Upward strokes, let absorb fully."], fr: ["Masser", "Mouvements ascendants, laisser pénétrer."] },
    ],
  },
  {
    id: "serum-eclat",
    world: "botanical",
    sub: "serums",
    name: { en: "Radiance & Even Tone Serum", fr: "Sérum Éclat & Teint Unifié" },
    short: { en: "Natural luminosity.", fr: "Éclat naturel." },
    lede: {
      en: "Argan, prickly pear and S'ad. The S'ad oil lends a natural golden note to the skin. Illuminates, evens the complexion, reduces dark spots.",
      fr: "Argan, figue de barbarie et S'ad. L'huile de S'ad apporte une note dorée naturelle à la peau. Illumine, unifie la carnation, réduit les taches.",
    },
    tags: ["Pure Argan", "Prickly Pear", "S'ad (Chufa)", "Anti-age", "Amber glass", "30 ml"],
    moq: 40,
    formats: ["30 ml", "50 ml"],
    lead: "3 weeks",
    images: ["/brand_photos/brand-lifestyle-3.jpg"],
  },
  {
    id: "serum-cheveux",
    world: "botanical",
    sub: "serums",
    name: { en: "Fortifying Hair Serum", fr: "Sérum Cheveux Fortifiant" },
    short: { en: "Anti-hair loss.", fr: "Anti-chute." },
    lede: {
      en: "Castor (growth and thickness), black seed (anti-loss, scalp), argan (shine and lightness). The most complete natural hair formula.",
      fr: "Ricin (pousse et épaisseur), nigelle (anti-chute, cuir chevelu), argan (brillance et légèreté). La formule capillaire naturelle la plus complète.",
    },
    tags: ["Castor", "Black Seed", "Pure Argan", "Fortifying", "Amber glass", "50 ml"],
    moq: 50,
    formats: ["50 ml", "100 ml"],
    lead: "2 weeks",
    images: ["/brand_photos/brand-lifestyle-4.jpg"],
  },
  {
    id: "serum-sourcils-cils",
    world: "botanical",
    sub: "serums",
    name: { en: "Brow & Lash Serum", fr: "Sérum Sourcils & Cils" },
    short: { en: "Growth and density.", fr: "Pousse et densité." },
    lede: {
      en: "Pure castor (powerful densifier), prickly pear (regenerating), rose (soothing). A serum formulated for the delicate eye area. Results in three weeks.",
      fr: "Ricin pur (densifiant puissant), figue de barbarie (régénérant), rose (apaisante). Formule sérum pour la zone délicate du regard. Résultats en trois semaines.",
    },
    tags: ["Castor", "Prickly Pear", "Damask Rose", "Fortifying", "Glass jar"],
    moq: 60,
    formats: ["10 ml"],
    lead: "2 weeks",
    images: ["/brand_photos/packaging-2.jpg"],
  },
  {
    id: "serum-contour-yeux",
    world: "botanical",
    sub: "serums",
    name: { en: "Eye Contour Serum", fr: "Sérum Contour Yeux" },
    short: { en: "Anti-wrinkle for the eyes.", fr: "Anti-rides yeux." },
    lede: {
      en: "Ultra-concentrated prickly pear, S'ad as a natural decongestant, rose tonic. The gentlest serum for the most delicate area.",
      fr: "Figue de barbarie ultra-concentrée, S'ad décongestionnant naturel, rose tonifiante. Le sérum le plus doux pour la zone la plus délicate.",
    },
    tags: ["Prickly Pear", "S'ad (Chufa)", "Damask Rose", "Anti-age", "Glass jar"],
    moq: 50,
    formats: ["10 ml", "15 ml"],
    lead: "3 weeks",
    images: ["/brand_photos/packaging-3.jpg"],
  },
  {
    id: "serum-vergetures",
    world: "botanical",
    sub: "serums",
    name: { en: "Anti-Stretch Mark Body Serum", fr: "Sérum Corps Anti-Vergetures" },
    short: { en: "Body care, long term.", fr: "Soin corps, longue durée." },
    lede: {
      en: "Repairing argan, tightening castor, regenerating black seed. A daily massage on targeted areas. Natural and effective over time.",
      fr: "Argan réparateur, ricin tenseur, nigelle régénérante. Massage quotidien sur les zones ciblées. Naturel et efficace sur la durée.",
    },
    tags: ["Pure Argan", "Castor", "Black Seed", "Hydrating", "Amber glass", "100 ml"],
    moq: 50,
    formats: ["100 ml", "200 ml"],
    lead: "2 weeks",
    images: ["/brand_photos/brand-lifestyle-5.jpg"],
  },

  // --- Gamme 04: Eaux Florales & Hydrolats (6) ---
  {
    id: "eau-rose-dades",
    world: "botanical",
    sub: "hydrolats",
    name: { en: "Pure Dades Rose Water", fr: "Eau de Rose Pure du Dadès" },
    short: { en: "Moroccan classic.", fr: "Classique marocain." },
    lede: {
      en: "Rosa Damascena steam-distilled in the Dades Valley. The most-used hydrosol in Moroccan homes for generations. Tonic, soothing, balances the skin's natural pH.",
      fr: "Rosa Damascena distillée à la vapeur dans la vallée du Dadès. Le produit le plus utilisé dans les foyers marocains depuis des générations. Tonifie, apaise, équilibre le pH naturel.",
    },
    ritual: "Classique Marocain",
    tags: ["Damask Rose", "Soothing", "Glass jar", "100 ml", "200 ml", "100% Natural"],
    moq: 60,
    formats: ["100 ml", "200 ml"],
    lead: "2 weeks",
    origin: "Dades Valley",
    images: ["/brand_photos/packaging-4.jpg"],
  },
  {
    id: "eau-fleur-oranger",
    world: "botanical",
    sub: "hydrolats",
    name: { en: "Pure Orange Blossom Water", fr: "Eau de Fleur d'Oranger Pure" },
    short: { en: "Fès tradition.", fr: "Tradition de Fès." },
    lede: {
      en: "Citrus Aurantium distilled in Fès and Meknès. The most-used hydrosol in Morocco: culinary, cosmetic, aromatic. Soothing, anti-stress, harmonising.",
      fr: "Citrus Aurantium distillée à Fès et Meknès. L'hydrolat le plus utilisé au Maroc: culinaire, cosmétique, aromatique. Apaisante, anti-stress, harmonisante.",
    },
    ritual: "Tradition de Fès",
    tags: ["Orange Blossom", "Soothing", "Glass jar", "100 ml", "200 ml", "100% Natural"],
    moq: 60,
    formats: ["100 ml", "200 ml"],
    lead: "2 weeks",
    origin: "Fès / Meknès",
    images: ["/brand_photos/packaging-5.jpg"],
  },
  {
    id: "hydrolat-romarin",
    world: "botanical",
    sub: "hydrolats",
    name: { en: "Rosemary Hydrosol", fr: "Hydrolat de Romarin" },
    short: { en: "Hair growth and tone.", fr: "Pousse et tonus capillaire." },
    lede: {
      en: "Rosmarinus officinalis from Morocco's mountains. Global hair-care trend 2026. Stimulates scalp circulation, reduces hair loss, brings shine.",
      fr: "Rosmarinus officinalis des montagnes marocaines. Tendance mondiale capillaire 2026. Stimule la circulation du cuir chevelu, réduit la chute, brillance.",
    },
    ritual: "Tendance 2026",
    tags: ["Rosemary", "Fortifying", "Energising", "Glass jar", "100 ml"],
    moq: 70,
    formats: ["100 ml", "200 ml"],
    lead: "2 weeks",
    origin: "Atlas",
    images: ["/brand_photos/packaging-1.jpg"],
  },
  {
    id: "hydrolat-lavande",
    world: "botanical",
    sub: "hydrolats",
    name: { en: "Atlas Lavender Hydrosol", fr: "Hydrolat de Lavande Atlas" },
    short: { en: "Soothing and healing.", fr: "Apaisant et cicatrisant." },
    lede: {
      en: "Atlas lavender, artisanal distillation. Superior to ordinary lavender. Anti-acne, suits sensitive skin, gentle disinfectant. Floral, herbaceous.",
      fr: "Lavande de l'Atlas, distillation artisanale. Qualité supérieure. Anti-acné, peaux sensibles, désinfectante douce. Floral et herbacé.",
    },
    tags: ["Atlas Lavender", "Soothing", "Glass jar", "100 ml"],
    moq: 60,
    formats: ["100 ml", "200 ml"],
    lead: "2 weeks",
    origin: "Atlas",
    images: ["/brand_photos/packaging-2.jpg"],
  },
  {
    id: "hydrolat-neroli",
    world: "botanical",
    sub: "hydrolats",
    name: { en: "Neroli Hydrosol", fr: "Hydrolat de Néroli" },
    short: { en: "Luxury anti-age.", fr: "Luxe anti-âge." },
    lede: {
      en: "Bitter orange blossom water, more concentrated and more luxurious than the classic. Anti-wrinkle and regenerating for mature skin. Deep, enveloping floral fragrance.",
      fr: "Eau de fleur d'oranger amère, plus concentrée et plus luxueuse que la classique. Anti-rides et régénérante pour peaux matures. Parfum floral profond et envoûtant.",
    },
    ritual: "Luxe Anti-âge",
    tags: ["Neroli", "Anti-age", "Glass jar", "50 ml", "100 ml"],
    moq: 50,
    formats: ["50 ml", "100 ml"],
    lead: "3 weeks",
    images: ["/brand_photos/packaging-3.jpg"],
  },
  {
    id: "brume-duo",
    world: "botanical",
    sub: "hydrolats",
    name: { en: "Rose & Orange Blossom Tonic Mist", fr: "Brume Tonique Rose & Fleur d'Oranger" },
    short: { en: "Emblematic duo.", fr: "Duo emblématique." },
    lede: {
      en: "Morocco's two emblematic hydrosols combined: Dades rose and Fès orange blossom. The best of both worlds in one bottle. A tonic and soothing daily mist.",
      fr: "Les deux hydrolats emblématiques du Maroc réunis: rose du Dadès et fleur d'oranger de Fès. Le meilleur des deux mondes dans une seule brume. Tonique et apaisante.",
    },
    tags: ["Damask Rose", "Orange Blossom", "Soothing", "Glass jar", "100 ml", "200 ml"],
    moq: 60,
    formats: ["100 ml", "200 ml"],
    lead: "2 weeks",
    images: ["/brand_photos/packaging-4.jpg"],
  },

  // --- Gamme 06: Huiles de Massage Parfumées (6) ---
  {
    id: "massage-argan-oud",
    world: "botanical",
    sub: "massage",
    name: { en: "Argan & Oud Massage Oil", fr: "Huile de Massage Argan & Oud" },
    short: { en: "Gulf luxury, premium.", fr: "Luxe du Golfe, premium." },
    lede: {
      en: "Argan and natural oud extract. Oud is a deep cultural tradition in the Gulf. Warm, woody, luxurious. The premium product of the range.",
      fr: "Argan et extrait naturel d'oud. L'oud est une tradition culturelle profonde dans le Golfe. Chaud, boisé, luxueux. Le produit le plus premium de la gamme.",
    },
    ritual: "Premium Golfe",
    tags: ["Pure Argan", "Oud", "Massage", "Amber glass", "100 ml"],
    moq: 30,
    formats: ["50 ml", "100 ml"],
    lead: "3 weeks",
    images: ["/brand_photos/packaging-5.jpg"],
  },
  {
    id: "massage-argan-rose",
    world: "botanical",
    sub: "massage",
    name: { en: "Argan & Rose Massage Oil", fr: "Huile de Massage Argan & Rose" },
    short: { en: "Spa favourite.", fr: "Favori des spas." },
    lede: {
      en: "Argan and Dades rose essential oil. The luxurious classic of spa care. Exceptional natural floral fragrance, silk-soft skin after the massage.",
      fr: "Argan et huile essentielle de rose du Dadès. Le classique luxueux des soins spa. Parfum floral naturel exceptionnel, peau de soie après le soin.",
    },
    ritual: "Spa Favori",
    tags: ["Pure Argan", "Damask Rose", "Massage", "Amber glass", "100 ml"],
    moq: 40,
    formats: ["100 ml", "200 ml"],
    lead: "2 weeks",
    origin: "Dades Valley",
    images: ["/brand_photos/argan-oil-dropper.jpg"],
  },
  {
    id: "corps-figue-saad",
    world: "botanical",
    sub: "massage",
    name: { en: "Prickly Pear & S'ad Body Oil", fr: "Huile Corps Figue & S'ad" },
    short: { en: "Ancestral feminine gesture.", fr: "Geste féminin ancestral." },
    lede: {
      en: "Prickly pear (ultra-nourishing, silky) and S'ad oil (unique earthy-sweet fragrance). Care and perfume in a single gesture. Quick absorption, no greasy film.",
      fr: "Figue de barbarie (ultra-nourrissante, soyeuse) et huile de S'ad (parfum naturel unique terreux-doux). Le soin et le parfum en un seul geste. Pénétration rapide sans film gras.",
    },
    tags: ["Prickly Pear", "S'ad (Chufa)", "Hydrating", "Amber glass", "100 ml"],
    moq: 40,
    formats: ["100 ml"],
    lead: "2 weeks",
    images: ["/brand_photos/brand-lifestyle-2.jpg"],
  },
  {
    id: "massage-argan-jasmin",
    world: "botanical",
    sub: "massage",
    name: { en: "Argan & Jasmine Massage Oil", fr: "Huile de Massage Argan & Jasmin" },
    short: { en: "Relaxing, enveloping.", fr: "Relaxant, enveloppant." },
    lede: {
      en: "Argan and Moroccan jasmine. An enveloping floral fragrance, a natural relaxant. For full-body relaxation massage. A naturally golden colour.",
      fr: "Argan et jasmin du Maroc. Parfum floral envoûtant, décontractant naturel. Pour massage relaxant corps complet. Couleur dorée naturelle.",
    },
    tags: ["Pure Argan", "Jasmine", "Massage", "Soothing", "Amber glass", "100 ml"],
    moq: 40,
    formats: ["100 ml"],
    lead: "2 weeks",
    images: ["/brand_photos/brand-lifestyle-1.jpg"],
  },
  {
    id: "corps-argan-musc",
    world: "botanical",
    sub: "massage",
    name: { en: "Argan & White Musk Body Oil", fr: "Huile Corps Argan & Musc Blanc" },
    short: { en: "Alcohol-free musk.", fr: "Musc sans alcool." },
    lede: {
      en: "Argan and natural white musk. A soft, warm, enveloping fragrance. Alcohol-free, respects all cultural values. Very strong demand in the Gulf and Morocco.",
      fr: "Argan et musc blanc naturel. Parfum doux, chaud, enveloppant. Sans alcool, respecte toutes les valeurs culturelles. Très forte demande au Golfe et au Maroc.",
    },
    tags: ["Pure Argan", "White Musk", "Massage", "Amber glass", "100 ml"],
    moq: 40,
    formats: ["100 ml"],
    lead: "2 weeks",
    images: ["/brand_photos/brand-lifestyle-3.jpg"],
  },
  {
    id: "chauffante-cannelle",
    world: "botanical",
    sub: "massage",
    name: { en: "Argan & Cinnamon Warming Oil", fr: "Huile Chauffante Argan & Cannelle" },
    short: { en: "Warming effect.", fr: "Effet chauffant." },
    lede: {
      en: "Argan and natural Moroccan cinnamon. A natural warming effect that stimulates circulation. Ideal for muscle massage, drainage and lymphatic work. Spicy, enveloping fragrance.",
      fr: "Argan et cannelle naturelle du Maroc. Effet chauffant naturel, stimule la circulation. Idéal massage musculaire, drainage et travail lymphatique. Parfum épicé envoûtant.",
    },
    tags: ["Pure Argan", "Cinnamon", "Massage", "Energising", "Amber glass", "100 ml"],
    moq: 40,
    formats: ["100 ml"],
    lead: "2 weeks",
    images: ["/brand_photos/brand-lifestyle-4.jpg"],
  },

  // ============================================================
  // HERITAGE, 3 curated B2B Packs
  // ============================================================
  {
    id: "pack-nila-oranger",
    world: "heritage",
    sub: "packs",
    name: { en: "Nila & Orange Blossom Pack", fr: "Pack Nila & Fleur d'Oranger" },
    short: { en: "Glow · softness · relaxation.", fr: "Éclat · douceur · relaxation." },
    lede: {
      en: "A complete hammam ritual: Pure Argan Oil, the signature Nila & Orange Blossom Scrub, the Nila & Orange Blossom Beldi Soap, and the pure Orange Blossom Hydrosol. Composed for hôtels and spas seeking the maison's blue-hour signature.",
      fr: "Un rituel hammam complet: Huile d'Argan Pure, le Gommage signature Nila & Fleur d'Oranger, le Savon Beldi Nila & Fleur d'Oranger, et l'Eau de Fleur d'Oranger Pure. Composé pour hôtels et spas qui veulent la signature bleutée de la maison.",
    },
    hero: true,
    ritual: "Heritage Pack",
    tags: ["Nila (Indigo)", "Orange Blossom", "Pure Argan", "Cedar box"],
    moq: 20,
    formats: ["4-piece box"],
    lead: "3 weeks",
    images: ["/brand_photos/gift-box-open.jpg", "/brand_photos/gift-boxes-overhead.jpg"],
    related: ["huile-argan", "gommage-nila", "savon-beldi-nila", "eau-fleur-oranger"],
  },
  {
    id: "pack-rose-aker-fassi",
    world: "heritage",
    sub: "packs",
    name: { en: "Rose & Aker Fassi Pack", fr: "Pack Rose & Aker Fassi" },
    short: { en: "Femininity · luxury · sensuality.", fr: "Féminité · luxe · sensualité." },
    lede: {
      en: "The maison's feminine signature: Pure Prickly Pear Seed Oil, the Aker Fassi & Rose Scrub, the Aker Fassi & Rose Beldi Soap, and the Pure Dades Rose Water. A four-piece ritual built for luxury hôtels and gift houses.",
      fr: "La signature féminine de la maison: Huile de Figue de Barbarie Pure, Gommage Aker Fassi & Rose, Savon Beldi Aker Fassi & Rose, et Eau de Rose Pure du Dadès. Un rituel quatre pièces pour hôtels luxe et maisons cadeaux.",
    },
    ritual: "Heritage Pack",
    tags: ["Damask Rose", "Aker Fassi", "Prickly Pear", "Cedar box"],
    moq: 20,
    formats: ["4-piece box"],
    lead: "3 weeks",
    images: ["/brand_photos/gift-box-flat.jpg", "/brand_photos/gift-boxes-overhead.jpg"],
    related: ["huile-figue-barbarie", "gommage-aker-fassi", "savon-beldi-aker-fassi", "eau-rose-dades"],
  },
  {
    id: "pack-rituel-naturel",
    world: "heritage",
    sub: "packs",
    name: { en: "Natural Ritual Pack", fr: "Pack Rituel Naturel" },
    short: { en: "Authenticity · purity · tradition.", fr: "Authenticité · pureté · tradition." },
    lede: {
      en: "The authenticity pack: Pure S'ad Oil, the Ghassoul & Argan Body Mask, the Ghassoul & Argan Beldi Soap, and the Pure Orange Blossom Hydrosol. The maison's most grounded ritual, for clients who want unmistakable Moroccan terroir.",
      fr: "Le pack authenticité: Huile de S'ad Pure, Masque Corps Ghassoul & Argan, Savon Beldi Ghassoul & Argan, et Eau de Fleur d'Oranger Pure. Le rituel le plus ancré de la maison, pour les clients qui veulent un terroir marocain sans équivoque.",
    },
    ritual: "Heritage Pack",
    tags: ["S'ad (Chufa)", "Ghassoul", "Pure Argan", "Orange Blossom", "Cedar box"],
    moq: 20,
    formats: ["4-piece box"],
    lead: "3 weeks",
    images: ["/brand_photos/products-all-three.jpg", "/brand_photos/gift-box-open.jpg"],
    related: ["huile-saad", "masque-ghassoul-argan", "savon-beldi-ghassoul", "eau-fleur-oranger"],
  },
];

/**
 * Lookup by product id. Used by the inquiry sidebar / TwoStepForm to resolve
 * names for items stored in localStorage by id.
 *
 * The public site reads products from Supabase via lib/data/products.ts; this
 * helper exists purely so client components can render product names without
 * a network round-trip on every cart change. Stays in sync with the seed.
 */
export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
